### ISSUE TITLE
Error upon startup

### ISSUE THREAD

**Issue by delboychad** [WilliamVenner/blackhole#9]
When the user logs in and startup applications begin to start the following error popups for Blackhole.
<img width="309" alt="image" src="https://user-images.githubusercontent.com/52761190/159186493-d0485fac-ff40-48d1-a153-1a0cf1c8b739.png">

**Comment by WilliamVenner** [comment]
It is so strange that these random errors (that seemingly have no bad side effects) keep popping up despite no code changes.
